name: finals
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  file_picker: ^8.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
