// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4IpYWOCM8DETYuquFV0zZ9I_mUwNV5Y',
    appId: '1:319283916711:web:9764ad1267a0417f359082',
    messagingSenderId: '319283916711',
    projectId: 'final-project-e09b5',
    authDomain: 'final-project-e09b5.firebaseapp.com',
    storageBucket: 'final-project-e09b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrIOtTJQdrmW3DsQ_SmSww6hIdyEg7va4',
    appId: '1:319283916711:android:06f24422355fe066359082',
    messagingSenderId: '319283916711',
    projectId: 'final-project-e09b5',
    storageBucket: 'final-project-e09b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ5nujK__ErKhEKYRu4A--oJbVJwqEApI',
    appId: '1:319283916711:ios:97cec96d99a39c73359082',
    messagingSenderId: '319283916711',
    projectId: 'final-project-e09b5',
    storageBucket: 'final-project-e09b5.appspot.com',
    iosBundleId: 'com.example.finals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ5nujK__ErKhEKYRu4A--oJbVJwqEApI',
    appId: '1:319283916711:ios:97cec96d99a39c73359082',
    messagingSenderId: '319283916711',
    projectId: 'final-project-e09b5',
    storageBucket: 'final-project-e09b5.appspot.com',
    iosBundleId: 'com.example.finals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm4IpYWOCM8DETYuquFV0zZ9I_mUwNV5Y',
    appId: '1:319283916711:web:46c789505d2d1ec5359082',
    messagingSenderId: '319283916711',
    projectId: 'final-project-e09b5',
    authDomain: 'final-project-e09b5.firebaseapp.com',
    storageBucket: 'final-project-e09b5.appspot.com',
  );
}
